### ISSUE TITLE
Private repo?

### ISSUE THREAD

**Issue by panpan-lin** [Endangered-Pets/endangered-pets-browser-extension#1]
Just tried it out it looks awesome! There are certainly design talent in the group! Trying to show it to my colleagues, but the repo is private. Is there any consideration for making it private? Could we make it public?

Maybe better still, could a GitHub org for the project be created and put all the related repos (both the extension and the website) under it?

**Comment by rossmccrann** [comment]
Hi Pan Pan, 
Apologies for the delay, I have created a GitHub Organisation titled "Endangered-Pets" which contains the 2 repos (browser-extension and website) which are now both public. Let me know if there's anything else!
