### ISSUE TITLE
pangolin size and scrollbar

### ISSUE THREAD

**Issue by panpan-lin** [Endangered-Pets/endangered-pets-browser-extension#2]
It seems to me that depending on screen size, a scenario can occur where the pangolin is quite big in the screen and a scrollbar appears (see screenshot below).

<img width="641" alt="Screenshot 2020-02-06 at 12 02 38" src="https://user-images.githubusercontent.com/22054715/74229677-c3c02900-4cba-11ea-8442-cddab168e062.png">

**Comment by peterpoliwoda** [comment]
He is a cute one I have to say 😄
